@startuml

' Configurações visuais
skinparam classAttributeIconSize 0
skinparam classBackgroundColor White
skinparam classBorderColor Black
skinparam classArrowColor Black

' --- Classes de Usuário ---

abstract class Usuario {
    # id: int
    # nome: string
    # email: string
    # senha: string
    # tipo: Enum ['admin', 'cliente']
    + login(email, senha): bool
    + logout(): void
    {abstract} + enderecoPaginaInicial(): string
}

class Administrador {
    + excluirUsuario(id: int): void
    + listarUsuarios(idAdmin: int): List<Usuario>
}

class Cliente {
    - nomeEmpresa: string
    + getNomeEmpresa(): string
}

' Herança
Usuario <|-- Administrador
Usuario <|-- Cliente

' --- Classes de Domínio (Estoque) ---

class Produto {
    - id: int
    - sku: string
    - nome: string
    - descricao: string
    - preco: float
    - quantidade: int
    - estoqueMinimo: int
    - id_usuario: int
    - id_fornecedor: int
    - id_categoria: int
    + salvar(): int
    + listarPorUsuario(id_usuario: int): List<Produto>
    + atualizarQuantidade(id, qtd, id_user): void
    + excluirProduto(id, id_user): void
    + buscarPorId(id, id_user): Produto
    + atualizar(...): void
}

class Fornecedor {
    - id: int
    - nomeEmpresa: string
    - cnpj: string
    - email: string
    - telefone: string
    - id_usuario: int
    + salvar(): void
    + listarFornecedores(id_usuario: int): List<Fornecedor>
    + excluirFornecedor(id_user, id_forn): void
    + atualizar(...): void
}

class Categoria {
    - id: int
    - nome: string
    - id_usuario: int
    + salvar(): void
    + listarCategorias(id_usuario: int): List<Categoria>
    + excluirCategoria(id_user, id_cat): void
    + atualizar(...): void
}

class Movimentacao {
    - id: int
    - tipo: Enum ['entrada', 'saida']
    - quantidade: int
    - data: DateTime
    - motivo: string
    - id_produto: int
    - id_usuario: int
    + registrar(): void
    + listarPorUsuario(id_usuario: int): List<Movimentacao>
}

' --- Relacionamentos ---

' Admin gerencia Clientes
Administrador "1" .right.> "*" Cliente : gerencia >

' Cliente possui seus dados (Multi-tenancy / Isolamento)
Cliente "1" -- "*" Produto : possui >
Cliente "1" -- "*" Fornecedor : possui >
Cliente "1" -- "*" Categoria : possui >

' Relação de autoria da movimentação
Cliente "1" -- "*" Movimentacao : registra >

' Relacionamentos do Produto
' 0..1 significa que o fornecedor/categoria pode ser nulo (se for deletado)
Produto "*" -- "0..1" Fornecedor : fornecido por >
Produto "*" -- "0..1" Categoria : pertence a >

' Composição: Movimentação só existe se houver produto
Produto "1" *-- "*" Movimentacao : histórico >

@enduml